//
//  AppCommunicator.swift
//  iListenOnWatch Extension
//
//  Created by 林祐正 on 2021/4/13.
//  Copyright © 2021 SmartFun. All rights reserved.
//

import Foundation
import Flynn
import WatchConnectivity

enum AppConnectStatus {
    case OK,NotSupported,
         NotActived,NotReachable
}

protocol WCSessionProtocol {
    @discardableResult
    func beSession(
        activationDidCompleteWith activationState: WCSessionActivationState, error: Error?) -> Self
    @discardableResult
    func beSession(didReceiveMessage message: [String : Any]) -> Self
    @discardableResult
    func beSession(
        didReceiveMessage message: [String : Any],
        replyHandler: @escaping ([String : Any]) -> Void) -> Self
    @discardableResult
    func beSession(
        _ session: WCSession,
        didReceiveApplicationContext applicationContext: [String : Any]) -> Self
}
extension WCSessionProtocol {
    func beSession(
        _ session: WCSession,
        didReceiveApplicationContext applicationContext: [String : Any]) -> Self {
        return self
    }
}

fileprivate class AppConnector: NSObject,WCSessionDelegate {
    static let shared = AppConnector()
    let wcSession: WCSession = WCSession.default
    var sender: WCSessionProtocol?
    
    override init() {
        super.init()
        if WCSession.isSupported() {
            wcSession.delegate = self
            wcSession.activate()
        }
    }
    
    // 檢查連接狀況
    func checkConnectStatus() -> AppConnectStatus {
        if !WCSession.isSupported() {
            // 目前iPhone不支援與iWatch通訊
            return .NotSupported
        }
        if WCSession.default.activationState != .activated{
            return .NotActived
        }
        if !WCSession.default.isReachable {
            return .NotReachable
        }
        return .OK
    }
    
    // MARK: - Delegate implements
    func session(
        _ session: WCSession,
        activationDidCompleteWith activationState: WCSessionActivationState,
        error: Error?) {
        sender?.beSession(
            activationDidCompleteWith: activationState, error: error)
    }
    func session(_ session: WCSession, didReceiveMessage message: [String : Any]) {
        sender?.beSession(didReceiveMessage: message)
    }
    func session(
        _ session: WCSession,
        didReceiveMessage message: [String : Any], replyHandler: @escaping ([String : Any]) -> Void) {
        sender?.beSession(didReceiveMessage: message, replyHandler: replyHandler)
        watchStore.dispatch(ReceivedAppMessageAction(message: message))
    }
}

class AppCommunicator: Actor {
    private let connector = AppConnector.shared
    private func _beRegisterSender(sender:WCSessionProtocol) {
        connector.sender = sender
    }
    private func _beCheckConnectStatus(
        sender:Actor,
        _ complete: @escaping (AppConnectStatus) -> Void) {
        let status = connector.checkConnectStatus()
        sender.unsafeSend {
            complete(status)
        }
    }
    private func _beSendMessage(
        sender: Actor,
        message: [String : Any],
        _ complete: (([String : Any]?,Error?) -> Void)?) {
        connector.wcSession.sendMessage(message) { (replyMessage) in
            if complete != nil {
                sender.unsafeSend {
                    complete!(replyMessage,nil)
                }
            }
        } errorHandler: { (error) in
            if complete != nil {
                sender.unsafeSend {
                    complete!(nil,error)
                }
            }
        }
    }
    private func _beUpdateApplicationContext(
        sender: Actor,
        appContext:[String : Any],_ complete: ((Error?) -> Void)?) {
        do {
            try connector.wcSession.updateApplicationContext(appContext)
            if complete != nil {
                sender.unsafeSend {
                    complete!(nil)
                }
            }
        } catch let error {
            if complete != nil {
                sender.unsafeSend {
                    complete!(error)
                }
            }
            fatalError("*** Unable to set up the audio session: \(error.localizedDescription) ***")
        }
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension AppCommunicator {

    @discardableResult
    public func beRegisterSender(sender: WCSessionProtocol) -> Self {
        unsafeSend { self._beRegisterSender(sender: sender) }
        return self
    }
    @discardableResult
    public func beCheckConnectStatus(sender: Actor, _ complete: @escaping (AppConnectStatus) -> Void) -> Self {
        unsafeSend { self._beCheckConnectStatus(sender: sender, complete) }
        return self
    }
    @discardableResult
    public func beSendMessage(sender: Actor, message: [String : Any], _ complete: (([String : Any]?,Error?) -> Void)?) -> Self {
        unsafeSend { self._beSendMessage(sender: sender, message: message, complete) }
        return self
    }
    @discardableResult
    public func beUpdateApplicationContext(sender: Actor, appContext: [String : Any], _ complete: ((Error?) -> Void)?) -> Self {
        unsafeSend { self._beUpdateApplicationContext(sender: sender, appContext: appContext, complete) }
        return self
    }

}
