//
//  DataConverter.swift
//  iListenOnWatch Extension
//
//  Created by 林祐正 on 2021/5/3.
//  Copyright © 2021 SmartFun. All rights reserved.
//

import Foundation
import Flynn
import UIKit

class DataConverter: Actor {
    private func _beConvertBetween<T1: Codable,T2: Codable>(
        sender: Actor,from: T1, to type: T2.Type,
        _ complete: @escaping (T2) -> Void) {
        do {
            let jsonData = try JSONEncoder().encode(from)
            let jsonString = String(data: jsonData, encoding: .utf8)
            let result = jsonString?.toEntity(to: type)
            if result != nil {
                sender.unsafeSend {
                    complete(result!)
                }
            }
        } catch {
            print(error.localizedDescription)
        }
    }
    private func _beEntityToJson<T: Codable>(
        sender:Actor,from entity: T,
        _ complete: @escaping (String) -> Void){
        do {
            let jsonData = try JSONEncoder().encode(entity)
            let jsonString = String(data: jsonData, encoding: .utf8) ?? ""
            sender.unsafeSend {
                complete(jsonString)
            }
        } catch {
            print(error.localizedDescription)
        }
    }
    
    private func _beDecodeQrCode(
        sender:Actor, image: UIImage,
        _ complete:@escaping([String]) -> Void) {
        var messages: [String] = []
        if let features = detectQRCode(image), !features.isEmpty{
            for case let row as CIQRCodeFeature in features{
                let qrcodeMsg = row.messageString ?? ""
                if !qrcodeMsg.isEmpty {
                    messages.append(qrcodeMsg)
                }
            }
            if messages.count > 0 {
                sender.unsafeSend {
                    complete(messages)
                }
            }
        }
    }
    
    private func detectQRCode(_ image: UIImage?) -> [CIFeature]? {
        if let image = image, let ciImage = CIImage.init(image: image){
            var options: [String: Any]
            let context = CIContext()
            options = [CIDetectorAccuracy: CIDetectorAccuracyHigh]
            let qrDetector = CIDetector(ofType: CIDetectorTypeQRCode, context: context, options: options)
            if ciImage.properties.keys.contains((kCGImagePropertyOrientation as String)){
                options = [CIDetectorImageOrientation: ciImage.properties[(kCGImagePropertyOrientation as String)] ?? 1]
            } else {
                options = [CIDetectorImageOrientation: 1]
            }
            let features = qrDetector?.features(in: ciImage, options: options)
            return features
            
        }
        return nil
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension DataConverter {

    @discardableResult
    public func beConvertBetween<T1: Codable,T2: Codable>(sender: Actor, from: T1, to type: T2.Type, _ complete: @escaping (T2) -> Void) -> Self {
        unsafeSend { self._beConvertBetween(sender: sender, from: from, to: type, complete) }
        return self
    }
    @discardableResult
    public func beEntityToJson<T: Codable>(sender: Actor, from entity: T, _ complete: @escaping (String) -> Void) -> Self {
        unsafeSend { self._beEntityToJson(sender: sender, from: entity, complete) }
        return self
    }
    @discardableResult
    public func beDecodeQrCode(sender: Actor, image: UIImage, _ complete: @escaping([String]) -> Void) -> Self {
        unsafeSend { self._beDecodeQrCode(sender: sender, image: image, complete) }
        return self
    }
    
}
