//
//  RoleSelectionScenario.swift
//  Enrollment
//
//  Created by YuCheng on 2021/5/21.
//

import Foundation
import Flynn

class RoleSelectionScenario: Actor {
    private func _beActVisitor(_ complete:@escaping () -> Void) {
        UserDefaults.standard.setValue("c", forKey: "role_of_user")
        DispatchQueue.main.async {
            complete()
        }
    }
    private func _beVisitedUnit(_ complete:@escaping () -> Void) {
        UserDefaults.standard.setValue("Visited_Unit", forKey: "role_of_user")
        DispatchQueue.main.async {
            complete()
        }
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension RoleSelectionScenario {

    @discardableResult
    public func beActVisitor(_ complete: @escaping () -> Void) -> Self {
        unsafeSend { self._beActVisitor(complete) }
        return self
    }
    @discardableResult
    public func beVisitedUnit(_ complete: @escaping () -> Void) -> Self {
        unsafeSend { self._beVisitedUnit(complete) }
        return self
    }

}
