//
//  StartAppScenario.swift
//  Enrollment
//
//  Created by YuCheng on 2021/5/21.
//

import Foundation
import Flynn

class StartAppScenario: Actor {
    private func _beGetRoleOfUser(_ complete:@escaping (String) -> Void) {
        if let role =
            UserDefaults.standard.object(forKey: roleStoredKey) as? String {
            DispatchQueue.main.async {
                complete(role)
            }
        } else {
            DispatchQueue.main.async {
                complete("")
            }
        }
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension StartAppScenario {

    @discardableResult
    public func beGetRoleOfUser(_ complete: @escaping (String) -> Void) -> Self {
        unsafeSend { self._beGetRoleOfUser(complete) }
        return self
    }

}
